apiVersion: apps/v1
kind: Deployment
metadata:
  name: timesheetapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: timesheetapi
  template:
    metadata:
      labels:
        app: timesheetapi
    spec:
      containers:
      - name: timesheetapi
        image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/timesheetapi:latest
        ports:
        - containerPort: 80
